### ISSUE TITLE
SPI feature request

### ISSUE THREAD

**Issue by drbh** [ch32-rs/ch32v00x-hal#15]
Hi @andelf this is an awesome project, thank you for all the work on `ch320-rs`.

I there a plan for SPI support in the near future? 

I'd like to contribute but am still learning the basics of embedded development and will likely not be able to implement the protocol, however if I can assist with simple testing please let me know.

possibly helpful resource
- esp-rs SPI impl https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/spi/master.rs
- ch32v003fun example https://github.com/cnlohr/ch32v003fun/tree/master/examples/spi_24L01_tx

**note my target peripheral is the [nrf24l01](https://components101.com/wireless/nrf24l01-pinout-features-datasheet)

**Comment by andelf** [comment]
It should be an easy task. The preferred reference for CH32 is STM32's SPI peripheral. (Yes, these Chinese chip vendors made some effort to be compatible with STM32, you'll find almost the same register blocks).

Currently, I'm working on an all-on-one [Embassy](https://embassy.dev/) hal driver at https://github.com/ch32-rs/ch32-hal. `ch32v00x-hal` is the original HAL crate. `ch32v00x-hal` will be the crate for legacy HAL style embedded programming for now. I'll review and merge PRs here but I myself might not work on it.

An SPI demo is at https://github.com/ch32-rs/ch32-hal/blob/main/examples/ch32v003/src/bin/spi-lcd-st7735-cube.rs

**Comment by drbh** [comment]
Hi @andelf thanks for the information! I'm actually going to move over to the `ch32-hal` crate.

Thanks for adding the SPI demo, it is very helpful for understanding how to add other peripherals
