### ISSUE TITLE
Any news about SPI support?

### ISSUE THREAD

**Issue by okhsunrog** [ch32-rs/ch32v00x-hal#18]
Is this project still supported? Can I expect SPI support in a month or two?

**Comment by Noxime** [comment]
Hello! The individual chip HALs have been unified under one project, since they share so many internals. See https://github.com/ch32-rs/ch32-hal 😄 I have not personally tried it, but the readme does mention SPI as functional for the CH32V0xx series chips

**Comment by okhsunrog** [comment]
Thanks! I'll check it out

**Comment by andelf** [comment]
Close as completed. Thanks.
