### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by urish** [ch32-rs/ch32v00x-hal#3]
Just wanted to say thanks for the great blog series at https://noxim.xyz/blog/rust-ch32v003/. 

Yesterday I wanted to get Rust code running on a custom designed RISC-V MCU (Caravel, which we are using in [TinyTapeout](https://tinytapeout.com)). Thanks to your detailed write-up, I was able to [get a Rust Blinky to run](https://github.com/TinyTapeout/caravel-firmware-rs) in just under two hours!

So many thanks :-)

**Comment by Noxime** [comment]
Thank you for the kind words :) TTO has always been intriguing but never got around to it. Good luck in your endeavor and feel free to ask any questions if you hit (software side) issues
